services:
  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=${API_URL}
  api:
    build: ./app
    volumes:
      - pb_data:/pb_data
volumes:
  pb_data:
    name: "weatherman-data"