import Head from "next/head";

import { Canvas } from "@/canvas/Canvas";
import { variablesToNodesAndEdges } from "@/canvas/useNodesAndEdges";
import { fromJSON } from "@/types/variables";
import { api } from "@/utils/api";

export default function Home() {
  const { data } = api.json.load.useQuery({
    filename: "../simulator/test.json",
  });

  const { variables: rawVariables } = data ?? {
    variables: [],
  };

  const variables = rawVariables.map(fromJSON);

  const { nodes, edges } = variablesToNodesAndEdges(variables);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen w-screen overflow-hidden">
        <div className="overflow-scroll">
          Palette
          <pre>{JSON.stringify(data, undefined, 2)}</pre>
        </div>

        {nodes.length > 0 && (
          <Canvas
            // variables={variables}
            initialNodes={nodes}
            initialEdges={edges}
            onVariablesChanged={(next) => {
              // console.log(next);
            }}
          />
        )}
      </div>
    </>
  );
}
