import React from "react";

import { useSetAtom } from "jotai";
import Head from "next/head";

import { Canvas } from "@/canvas/Canvas";
import { initializeNodeNamesMapAtom } from "@/canvas/atoms";
import { variablesToNodesAndEdges } from "@/canvas/useNodesAndEdges";
import { type AnyVariableData } from "@/types/variables/allVariables";
import { api } from "@/utils/api";

export default function Home() {
  const { data } = api.json.load.useQuery({
    filename: "../simulator/test.json",
  });

  const { variables } = data ?? {
    variables: [],
  };

  const initializeNodeNamesMap = useSetAtom(initializeNodeNamesMapAtom);

  const { nodes, edges, nodeNameToId } = variablesToNodesAndEdges(
    variables as AnyVariableData[]
  );

  React.useEffect(() => {
    initializeNodeNamesMap(nodeNameToId);
  }, [nodeNameToId, initializeNodeNamesMap]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {nodes.length > 0 && (
        <Canvas
          // variables={variables}
          initialNodes={nodes}
          initialEdges={edges}
        />
      )}
    </>
  );
}
